os: osx
osx_image: xcode11.5
language: swift
script: xcodebuild clean test -workspace App/Quiz.xcworkspace -scheme "CI" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.5,name=iPhone 11" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO

